### ISSUE TITLE
Length prefixes `hh` and `ll` don't work

### ISSUE THREAD

**Issue by jornitski** [wdavidw/node-printf#19]
```js
require('printf')('%02hhx %02hx %02x %02lx %02llx', 1,2,3,4,5);
```

That should print out `01 02 03 04 05` but it actually prints `%02hhx 01 02 03 %02llx`

**Comment by wdavidw** [comment]
I'll have to trust you on this one, do you have an url where this is referenced ? Feel free to submit a pull request.

**Comment by jornitski** [comment]
If you want to verify, there are a few ways.  Use `printf` on mac: just run `printf "%02hhx" 1` in the shell.  You can also write a quick C program to verify.

Documentation you can just read the manpage: `man 3 printf`.  On my mac there's a table for lengths:

```
     o   An optional length modifier, that specifies the size of the argument.
         The following length modifiers are valid for the d, i, n, o, u, x, or
         X conversion:

         Modifier          d, i           o, u, x, X            n
         hh                signed char    unsigned char         signed char *
         h                 short          unsigned short        short *
         l (ell)           long           unsigned long         long *
         ll (ell ell)      long long      unsigned long long    long long *
         j                 intmax_t       uintmax_t             intmax_t *
         t                 ptrdiff_t      (see note)            ptrdiff_t *
         z                 (see note)     size_t                (see note)
         q (deprecated)    quad_t         u_quad_t              quad_t *
```

C99 and POSIX both describe it: http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html

```
The length modifiers and their meanings are:

hh
Specifies that a following d, i, o, u, x, or X conversion specifier applies to a signed char or unsigned char argument (the argument will have been promoted according to the integer promotions, but its value shall be converted to signed char or unsigned char before printing); or that a following n conversion specifier applies to a pointer to a signed char argument.
ll (ell-ell)
Specifies that a following d, i, o, u, x, or X conversion specifier applies to a long long or unsigned long long argument; or that a following n conversion specifier applies to a pointer to a long long argument.
```

**Comment by jornitski** [comment]
So the regular expression snippet for the length is `[hlL]?`.  That probably needs to be changed to something like `(hh?|ll?|L)`.  To avoid blowing up on more formats, its probably better to make that include everything else.

**Comment by wdavidw** [comment]
agreed

**Comment by costacosta** [comment]
@jornitski If you are still hung up on this, the printj module https://www.npmjs.com/package/printj seems to do the right thing:

```
> require('printj').sprintf('%02hhx %02hx %02x %02lx %02llx', 1,2,3,4,5);
'01 02 03 04 05'
```

**Comment by wdavidw** [comment]
or u could prepare a pull request : )

**Comment by jornitski** [comment]
@costacosta yeah we already switched over, I had started working on a fix here but we ran into more problems and it was easier to use a different library that just works.  Probably should close this.
